/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:73885a0c-9d40-4896-85cc-c1a6d11941e7",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_5HQMEiUov",
    "aws_user_pools_web_client_id": "2j4t42lq1e4ofppb1t1bkotpin",
    "oauth": {}
};


export default awsmobile;
